apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: blog
build:
  artifacts:
  - image: rolandpakai/client
    context: client
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: 'src/**/*.js'
          dest: .
  - image: rolandpakai/comments
    context: comments
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: rolandpakai/event-bus
    context: event-bus
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: rolandpakai/moderation
    context: moderation
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: rolandpakai/posts
    context: posts
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
  - image: rolandpakai/query
    context: query
    docker:
      dockerfile: Dockerfile
    sync:
      manual:
        - src: '*.js'
          dest: .
manifests:
  rawYaml:
  - infra/k8s/client-depl.yaml
  - infra/k8s/comments-depl.yaml
  - infra/k8s/event-bus-depl.yaml
  - infra/k8s/ingress-srv.yaml
  - infra/k8s/moderation-depl.yaml
  - infra/k8s/posts-depl.yaml
  - infra/k8s/posts-srv.yaml
  - infra/k8s/query-depl.yaml
